                <div class="row">
					<div class="col-md-12">
						<!-- BEGIN SAMPLE FORM PORTLET-->
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption font-green-haze">
									<i class="icon-user font-green-haze"></i>
									<span class="caption-subject bold uppercase"> Seguimiento de Oportunidad por Campa&ntilde;a</span>
								</div>
								<div class="actions">									
									<a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
									</a>
								</div>
							</div>
							<div class="portlet-body form">                            
								<form id="form_campana" method="post" action="<?php echo $this->basePath()?>/operador/oportunidad/campana2" role="form" class="form-horizontal">
									<div class="form-body">
                                                                        
                                    <div id="alertok"></div>
                                    <div id="alertnok"></div>
                                                                        
										<div class="form-group form-md-line-input">
											<div class="row text-center">
										<div class="col-md-4 col-md-push-4 form-group form-md-line-input has-info ">
											<select class="form-control" id="combo_campana" name="ID_CAMPANA" style="margin-top: 20px;">
												 <option value="0">Seleccione una Campa&ntilde;a</option>
                                            <?php for ($i=0;$i<count($combo_campana);$i++){                                                      
                                                      echo "<option value=".$combo_campana[$i]['ID_CAMPANA'].">".$combo_campana[$i]['NOMBRE_CAMPANA']."</option>\n";
                                               }        
                                                ?>
											</select>
											<label for="form_control_1" >Seleccione Campa&ntilde;a</label>
										</div>
                                        
                                        </div>
                                        <span class="input-group-btn btn-right text-center">
                                            <a id="busca_campana" class="btn green-haze">
                                                    <i class="fa fa-search"></i> &nbsp; Buscar oportunidades abiertas
                                            </a>
			                                </span> 
										</div>
                                    </div>
                                  </form>  
                                </div>
                            </div>
                        </div>
                   </div>

<script>
toastr.options = {
  "positionClass": "toast-top-center",
}
$("#busca_campana").click(function(){
    if($("#combo_campana").val()<1) {
        toastr.warning('Debe seleccionar una campaña');    
    }else{   
        $.ajax(
            {
            url : '<?php echo $this->basePath()."/operador/oportunidad/buscaopcampana"?>',
            type: "POST",
            data : {'ID_CAMPANA' : $("#combo_campana").val()},
            dataType : 'json',
            success : function(response) {                 
              if(response.flag!="true")
              {
                toastr.warning(response.descr);  
              }else{
                $("#form_campana").submit(); 
                toastr.success(response.descr); 
              }
            },
            error: function(jqXHR, textStatus, errorThrown) 
            {   
                toastr.error('Error! Favor contactar con administrador del sistema');                            
            }
        }); 
    }  
});

</script>                            