                <div class="row">
					<div class="col-md-12">
						<!-- BEGIN SAMPLE FORM PORTLET-->
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption font-green-haze">
									<i class="icon-user font-green-haze"></i>
									<span class="caption-subject bold uppercase"> Seguimiento de Oportunidad por Campa&ntilde;a</span>
								</div>
								<div class="actions">									
									<a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
									</a>
								</div>
							</div>
							<div class="portlet-body form">                            
								<form id="form_prospecto" action="<?php echo $this->basePath()?>/oportunidad/actualizardatos" role="form" class="form-horizontal">
									<div class="form-body">
                                                                        
                                    <div id="alertok"></div>
                                    <div id="alertnok"></div>
                                                                        
										<div class="form-group form-md-line-input">
											<div class="row text-center">
										<div class="col-md-4 col-md-push-4 form-group form-md-line-input has-info ">
											<select class="form-control" id="form_control_1" style="margin-top: 20px;">
												<option value=""></option>
												<option value="">Campaña liceo industrial XY</option>
												<option value="">Option 2</option>
												<option value="">Option 3</option>
												<option value="">Option 4</option>
											</select>
											<label for="form_control_1" >Seleccione Campa&ntilde;a</label>
										</div>
                                        
                                        </div>
                                        <span class="input-group-btn btn-right text-center">
                                            <a href="<?php echo $this->basePath()?>/operador/oportunidad/campana2" class="btn green-haze" type="button">
                                                    <i class="fa fa-search"></i> &nbsp; Buscar oportunidades abiertas
                                            </a>
			                                </span> 
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                   </div>

                            