													<span class="number">
													1 </span>
													<span class="desc">
													<i class="fa fa-check"></i> Ingreso de prospecto </span>
													</a>
												</li>
												<li>
													<a href="#tab2" data-toggle="tab" class="step">
													<span class="number">
													2 </span>
													<span class="desc">
													<i class="fa fa-check"></i> Selecci&oacute;n de Campa&ntilde;a / Sede / Carrera / Jornada  </span>
													</a>
												</li>												
											</ul>
											<div id="bar" class="progress progress-striped" role="progressbar">
												<div class="progress-bar progress-bar-success">
												</div>
											</div>
											<div class="tab-content">
												<div class="alert alert-danger display-none">
													<button class="close" data-dismiss="alert"></button>
													You have some form errors. Please check below.
												</div>
												<div class="alert alert-success display-none">
													<button class="close" data-dismiss="alert"></button>
													Your form validation is successful!
												</div>
												<div class="tab-pane active" id="tab1">	
                                                 <div class="form-group form-md-line-input form-md-floating-label">
                                                    <label class="control-label col-md-4"> <span class="required">
														 </span>
														</label>
                                                   <form id="busarut" action="<?php echo $this->basePath()?>/operador/oportunidad/buscarut">     
											         <div class="input-group col-md-3">											
								                        <div class="input-group-control">
													       <input type="text" class="form-control input-sm">
													       <label for="form_control_1">RUT</label>
                                                           <span class="help-block">Sin d&iacute;gito verificador</span>
												        </div>
												        <span class="input-group-btn btn-right">
												            <button class="btn green-haze" type="button"><i class="fa fa-search"></i></button>
												        </span>                                                        
											         </div>
                                                    </form>    
                                                </div>	
                                                <br />
                                                <br />			
                                                <br />														
													<!--div class="form-group">
														<label class="control-label col-md-3">Rut <span class="required">
														* </span>
														</label>
														<div class="col-md-4">
															<input type="text" class="form-control" name="rut"/>
															<span class="help-block">
															Sin d&iacute;gito verificador </span>
														</div>
													</div-->
													<div class="form-group">
														<label class="control-label col-md-3">Nombre <span class="required">
														* </span>
														</label>
														<div class="col-md-4">
															<input type="password" class="form-control" name="password" id="submit_form_password"/>
															<span class="help-block">
															Provide your password. </span>
														</div>
													</div>
													<div class="form-group">
														<label class="control-label col-md-3">Apellido Paterno <span class="required">
														* </span>
														</label>
														<div class="col-md-4">
															<input type="password" class="form-control" name="rpassword"/>
															<span class="help-block">
															Confirm your password </span>
														</div>
													</div>
                                                    <div class="form-group">
														<label class="control-label col-md-3">Apellido Materno <span class="required">
														* </span>
														</label>
														<div class="col-md-4">
															<input type="password" class="form-control" name="rpassword"/>
															<span class="help-block">
															Confirm your password </span>
														</div>
													</div>
												  <div class="form-group form-md-line-input">
											         <label class="control-label col-md-3">Estado</label>
							                         <div class="col-md-4">
												            <div class="input-group has-success">
												     	       <span class="input-group-addon">
												                    Cargado  &nbsp;&nbsp;<i class="fa fa-check"></i>
												     	       </span>
												     	            
												        <div class="form-control-focus">
												       </div>
												    </div>
											        </div>
										          </div>
                                                  <div class="form-group">
														<label class="control-label col-md-3">Correo <span class="required">
														* </span>
														</label>
														<div class="col-md-4">
															<input type="password" class="form-control" name="rpassword"/>
															<span class="help-block">
															Confirm your password </span>
														</div>
												   </div>
                                                   <div class="form-group">
														<label class="control-label col-md-3">Tel&eacute;fono <span class="required">
														* </span>
														</label>
														<div class="col-md-4">
															<input type="password" class="form-control" name="rpassword"/>
															<span class="help-block">
															Confirm your password </span>
														</div>
													</div>
                                                    <div class="form-group">
														<label class="control-label col-md-3">Celular <span class="required">
														* </span>
														</label>
														<div class="col-md-4">
															<input type="password" class="form-control" name="rpassword"/>
															<span class="help-block">
															Confirm your password </span>
														</div>
													</div>
                                                    <div class="form-group">
														<label class="control-label col-md-3">Direcci&oacute;n <span class="required">
														* </span>
														</label>
														<div class="col-md-4">
															<input type="password" class="form-control" name="rpassword"/>
															<span class="help-block">
															Confirm your password </span>
														</div>
													</div>
                                                    <div class="form-group">
														<label class="control-label col-md-3">Emp./Establecimiento  <span class="required">
														* </span>
														</label>
														<div class="col-md-4">
															<input type="password" class="form-control" name="rpassword"/>
															<span class="help-block">
															Confirm your password </span>
														</div>
													</div>
                                                  
                                                    
									