<?php
//LLamaremos a la session
use Zend\Session\Container;
$sid = new Container('base');
$usuario = $sid->offsetGet('usuario');
$sede = $sid->offsetGet('sede');
?>
<div class="row">
					<div class="col-md-12">
						<!-- BEGIN SAMPLE FORM PORTLET-->
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption font-green-haze">
									<i class="icon-star font-green-haze"></i>
									<span class="caption-subject bold uppercase"> Ingreso de Oportunidad</span>
								</div>
								<div class="actions">
									<a class="btn btn-circle btn-icon-only red" onclick="reset()">
									<i class="icon-trash"></i>
									</a>
									<a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
									</a>
								</div>
							</div>
							<div class="portlet-body form">                            
								<form id="form_prospecto" action="<?php echo $this->basePath()?>/operador/oportunidad/actualizardatos" role="form" class="form-horizontal">
									<div class="form-body">
                                        <div class="form-group form-md-line-input">
									       <div id="alertok"></div>
                                            <div id="alertnok"></div>
										</div>                                    
                                    
                                                                        
										<div class="form-group form-md-line-input">
											<label class="col-md-2 control-label" for="nueva_rut">Rut</label>
											<div class="col-md-2">
												<input type="text" class="form-control" id="nueva_rut" name="RUT">
												<div class="form-control-focus">
												</div>
                                                <span class="help-block">Sin puntos ni DV</span>
											</div>
                                            <span id="boton_buscar" class="input-group-btn btn-right ">
												            <a id="busca_rut" class="btn green-haze" ><i class="fa fa-search"></i></a>
			                                </span> 
										</div>
            <div id="div_form" class="hide">
										<div class="form-group form-md-line-input">
											<label class="col-md-2 control-label" for="nueva_nombre">Nombre</label>
											<div class="col-md-5">
												<input type="text" class="form-control" id="nueva_nombre" name="NOMBRE" required>
												<div class="form-control-focus">
												</div>												
											</div>
										</div>
										<div class="form-group form-md-line-input has-success">
											<label class="col-md-2 control-label" for="nueva_apellidop">Apellido Paterno</label>
											<div class="col-md-5">
												<input type="text" class="form-control" id="nueva_apellidop" name="AP_PATERNO" required>
												<div class="form-control-focus">
												</div>
											</div>
										</div>
										<div class="form-group form-md-line-input has-warning">
											<label class="col-md-2 control-label" for="nueva_apellidom">Apellido Materno</label>
											<div class="col-md-5">
												<input type="text" class="form-control" id="nueva_apellidom" name="AP_MATERNO" required>
												<div class="form-control-focus">
												</div>
                                                
											</div>
										</div>
										<div class="form-group form-md-line-input has-error">
											<label class="col-md-2 control-label" for="nueva_estado">Estado</label>
											<div class="col-md-2">
												<input type="text" class="form-control" id="nueva_estado" name="ESTADO" disabled>
												<div class="form-control-focus">
												</div>
											</div>
										</div>
										<!--div class="form-group form-md-line-input">
											<label class="col-md-2 control-label" for="form_control_1">Dropdown Input</label>
											<div class="col-md-10">
												<select class="form-control" id="form_control_1">
													<option value=""></option>
													<option value="">Option 1</option>
													<option value="">Option 2</option>
													<option value="">Option 3</option>
													<option value="">Option 4</option>
												</select>
												<div class="form-control-focus">
												</div>
											</div>
										</div-->
										<!--div class="form-group form-md-line-input has-success">
											<label class="col-md-2 control-label" for="form_control_1">Textarea</label>
											<div class="col-md-10">
												<textarea class="form-control" rows="3" placeholder="Enter more text"></textarea>
												<div class="form-control-focus">
												</div>
											</div>
										</div-->
                                        <div class="form-group form-md-line-input has-error">
											<label class="col-md-2 control-label" for="nueva_correo">Correo</label>
											<div class="col-md-5">                                            
												<input type="text" class="form-control" id="nueva_correo" name="CORREO" >
												<div class="form-control-focus">
												</div>
											</div>
										</div>
                                        <div class="form-group form-md-line-input has-error">
											<label class="col-md-2 control-label" for="nueva_tel">Tel&eacute;fono</label>
											<div class="col-md-5">
												<input type="text" class="form-control" id="nueva_tel" name="TELEFONO">
												<div class="form-control-focus">
												</div>
											</div>
										</div>
                                        <div class="form-group form-md-line-input has-error">
											<label class="col-md-2 control-label" for="nueva_celu">Celular</label>
											<div class="col-md-5">
												<input type="text" class="form-control" id="nueva_celu" name="CELULAR">
												<div class="form-control-focus">
												</div>
											</div>
										</div>
                                        <div class="form-group form-md-line-input has-error">
											<label class="col-md-2 control-label" for="nueva_direc">Direcci&oacute;n</label>
											<div class="col-md-5">
												<input type="text" class="form-control" id="nueva_direc" name="DIRECCION" >
												<div class="form-control-focus">
												</div>
											</div>
										</div>
                                        <div class="form-group form-md-line-input has-error">
											<label class="col-md-2 control-label" for="nueva_establec">Emp./Establecimiento</label>
											<div class="col-md-5">
												<input type="text" class="form-control" id="nueva_establec" name="EMPRESA_ESTABLEC" >
                                                <input type="hidden" name="USERNAME_ACTUALIZACION" value="<?php echo $usuario;?>" >
												<div class="form-control-focus">
												</div>
											</div>
										</div>									
									
                                    <table id="tablaprospecto" class="table table-hover">
									<thead>
									<tr>
										<th>
											 #
										</th>
										<th>
											 Correo
										</th>
										<th>
											 Tel&eacute;fono
										</th>
										<th>
											 Celular
										</th>
                                        <th>
										     Empresa/Establec. 
										</th>
                                        <th>
										     Direcci&oacute;n 
										</th>
                                        <th>
										    Usuario 
										</th>                                         
                                        <th>
										    Fecha 
										</th>
									</tr>
									</thead>
									<tbody id="nueva_bodytable">

									</tbody>
									</table>
									<div class="form-actions">
										<div class="row">
											<div class="col-md-offset-2 col-md-10">
												<a id="noleinteresa" onclick="nointeresa()" class="btn default hide"><i class="fa fa-thumbs-down"></i> &nbsp; No le interesa</a>
												<a id="actualizarDatos" class="btn blue"><i class="fa fa-save"></i> &nbsp; Actualizar Datos</a>
                                                <a id="mostrarpaso2" onclick="mostrarpaso2('<?php echo $usuario;?>')" class="btn green hide">Paso 2 - Asignar Campa&ntilde;a/Sede/Carrera</a>                                                
											</div>
										</div>
									</div>								
						<br />
                        <br />                        
                            </div>
        </div>                            
      <div id="div_campana" class="hide">                            
              <div class="portlet-body form">								
									<div class="form-body">
                                    <div class="row text-center">
										<div class="col-md-4 col-md-push-4 form-group form-md-line-input has-info ">
											<select class="form-control" id="combo_campana" name="ID_CAMPANA">
											</select>
											<label for="combo_campana"><strong>Campa&ntilde;a</strong></label>
										</div>
						             </div>
                                     <div class="row text-center">
										<div class="col-md-4 col-md-push-4 form-group form-md-line-input has-info ">
											<select onchange="buscaJornada()" class="form-control" id="combo_carrera" name="COD_CARRERA">

											</select>
											<label for="combo_carrera"><strong>Carrera</strong></label>
										</div>
						             </div>
                                     <div class="row text-center">
										<div class="col-md-4 col-md-push-4 form-group form-md-line-input has-info ">
											<select class="form-control" id="combo_jornada" name="JORNADA">

											</select>
											<label for="combo_jornada"><strong>Jornada</strong></label>
										</div>
						             </div>                                                                          
									<div class="form-actions noborder text-center">
										<a onclick="reset()" class="btn default">Gestionar Otro RUT</a>
                                        <a onclick="nuevaoportunidad()" class="btn blue">Ingresar Oportunidad</a>										
									</div>
								</form>
							</div>
                </div>
                            
                            
              	</div>              
                            
                          	</div>  
                            
                         	</div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
						</div>
                                      

       	</div> 
<div id="modal_confirm" class="modal fade" tabindex="-1" role="dialog"  data-keyboard="false">
									<div class="modal-dialog modal-lg">
										<div class="modal-content">
											<div class="modal-header">
												<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
												<h4 class="modal-title"><i class="icon-user"></i> &nbsp;Gesti&oacute;n de feedback de Oportunidad</h4>
											</div>
			<div id="bodymodal_detalle" class="modal-body">
											                 
                                                           
			 </div>
		</div>
    </div>
</div>                                
                                                                              
<script>
toastr.options = {
  "positionClass": "toast-top-center",
}
bootbox.setDefaults({
  locale: "es"
});
function reset()
{  
    toastr.success('Gestione otro rut');  
   $("#nueva_bodytable tr").remove();
   $('#noleinteresa').addClass('hide');
   $("#nueva_rut").attr('disabled',false);
   $('#mostrarpaso2').addClass('hide');
   $('#div_form').addClass('hide'); 
   $('#div_campana').addClass('hide'); 
   $('#form_prospecto').trigger("reset");
   
}
$("#busca_rut").click(function(){      
postData = {'RUT' : $('#nueva_rut').val()}
    $.ajax(
    {
        url : '<?php echo $this->basePath()."/operador/oportunidad/buscarut"?>',
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {
            $('#div_form').removeClass('hide');
            if(response.existe=="si"){  
                if(response.prospecto[0]['ESTADO']=="n"){var estado="NO MOLESTAR";}else{var estado="Interesado";}
                toastr.success('Prospecto encontrado');
                $("#nueva_nombre").val(response.prospecto[0]['NOMBRES']);
                $("#nueva_apellidop").val(response.prospecto[0]['AP_PATERNO']);
                $("#nueva_apellidom").val(response.prospecto[0]['AP_MATERNO']);
                $("#nueva_estado").val(estado);
                $("#nueva_correo").val(response.detalle[0]['CORREO']);
                $("#nueva_tel").val(response.detalle[0]['TELEFONO']);
                $("#nueva_celu").val(response.detalle[0]['CELULAR']);
                $("#nueva_direc").val(response.detalle[0]['DIRECCION']);
                $("#nueva_establec").val(response.detalle[0]['EMPRESA_ESTABLEC']);
                $("#nueva_bodytable").html(response.tabla);
                $("#nueva_rut").attr('disabled',true);
                $("#mostrarpaso2").removeClass("hide");
                $("#noleinteresa").removeClass("hide");
            }
            else{
             //   Command: toastr[success]("No existe prospecto");
                toastr.warning('No existe prospecto, ingresar datos'); 
                $("#actualizarDatos").html("<i class='fa fa-save'></i> &nbsp; Ingresar nuevo prospecto");
            // $("#alertok").html('<span class="alert alert-success"> '+response.desc+'</span>');                   
            }                                  
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {            
            toastr.warning("Error! Favor contactar con administrador del sistema"); 
        }
    });
});
function mostrarpaso2(user){
$('#div_campana').removeClass('hide');    
postData = {'user' : user}
$.ajax(
    {
        url : '<?php echo $this->basePath()."/operador/oportunidad/combospaso2"?>',
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {         
        var combo1 = $("#combo_campana");
        var combo2 = $("#combo_carrera");                  
         // Limpiamos combos
         combo1.find('option').remove();
         combo2.find('option').remove();         
         //Cagamos combo1
         $(response.campanas).each(function(i, v){ // indice, valor                    
         combo1.append('<option value="' + response.campanas[i]['ID_CAMPANA'] + '">' + response.campanas[i]['NOMBRE_CAMPANA'] + '</option>');
         })
         combo1.prop('disabled', false);
        
         //Cagamos combo2
         $(response.carreras).each(function(i, v){ // indice, valor                    
         combo2.append('<option value="' + response.carreras[i]['COD_CARRERA'] + '">' + response.carreras[i]['NOMBRE_CARRERA'] + '</option>');
         })
         combo2.prop('disabled', false);
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {            
            alert("Error ! Favor contactar con administrador del sistema"); 
        }
    });
}
function buscaJornada(){    
    var combo = $("#combo_carrera");
    postData = {'cod_carrera' : combo.find('option:selected').val(),
                'sede': '<?php echo $sede;?>'    }    
    $.ajax(
    {
        url : '<?php echo $this->basePath()."/operador/oportunidad/buscajornada"?>',
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {              
        var sel = $("#combo_jornada");
        sel.empty();
          $(response.jornada).each(function(i, v){ // indice, valor 
          if(response.jornada[i]=="V"){var text="Vespertina"}else{var text="Diurna"}                
         sel.append('<option value="' + response.jornada[i] + '">' + text + '</option>');
         })
         sel.prop('disabled', false);                      
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {            
            alert("error"); 
        }
    });
}
$('#actualizarDatos').click(function(){
bootbox.confirm("<strong>Esta seguro ?", function(result) {
if (result)
{   $("#nueva_rut").attr('disabled',false);
    var postData = $("#form_prospecto").serializeArray();    
    $.ajax(
    {
        url : '<?php echo $this->basePath()."/operador/oportunidad/actualizardatos"?>',
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {
                    if(response.status!="ok"){
                        toastr.warning(response.descripcion);
                      //  $("#alertnok").html('<span class="alert alert-danger">'+response.descripcion+'</span>'); 
                      
                    }else{
                        toastr.success(response.descripcion);
                        $("#nueva_rut").attr('disabled',true);
                        $("#mostrarpaso2").removeClass("hide");
                        $("#actualizarDatos").html("<i class='fa fa-save'></i> &nbsp; Actualizar datos");
                        $("#nueva_bodytable").html(response.tabla);   
                        $("#noleinteresa").removeClass("hide");                                                                                             
                        //$("#alertok").html('<span class="alert alert-success">'+response.descripcion+'</span>');    
                    }
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {
            toastr.error('Error ! Favor contactar con administrador del sistema');            
           // $("#alertnok").html('<span class="alert alert-success">Error en el env&iacute;o de datos al servidor</span>');      
        }
    });        
}else{
    toastr.info('Sin cambios'); 
} 
}); 
});
function nointeresa(){
    bootbox.confirm("<strong>Estas Seguro ?</strong>", function(result) {
        if (result){
            postData = {'estado' : 'n',
                        'rut': $("#nueva_rut").val()   } 
     $.ajax(
        {
          url : '<?php echo $this->basePath()."/operador/oportunidad/actualizarestado"?>',
            type: "POST",
            data : postData,
            dataType : 'json',
            success : function(response) {
                        $("#nueva_estado").val("NO MOLESTAR")
                        toastr.success(response.descr);
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {
            toastr.error('Error ! Favor contactar con administrador del sistema');            
           // $("#alertnok").html('<span class="alert alert-success">Error en el env&iacute;o de datos al servidor</span>');      
        }
    }); 
           toastr.success('Estado de prospecto cambio a <strong>NO MOLESTAR</strong>');
        }else{
           toastr.info('Estado de prospecto sin cambios'); 
        } 
});     
}
function nuevaoportunidad(){
bootbox.confirm("<strong>Estas Seguro ?</strong>", function(result) {
        if (result){
    $("#nueva_rut").attr('disabled',false);
    $("#nueva_estado").attr('disabled',false);
    var postData = $("#form_prospecto").serializeArray();    
       $.ajax(
        {
          url : '<?php echo $this->basePath()."/operador/oportunidad/nuevaoportunidad"?>',
            type: "POST",
            data : postData,
            dataType : 'json',
            success : function(response) {                        
                         $("#nueva_rut").attr('disabled',true);
                         $("#nueva_estado").attr('disabled',true);
                        toastr.success(response.descr);
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {
            toastr.error('Error ! Favor contactar con administrador del sistema');            
           // $("#alertnok").html('<span class="alert alert-success">Error en el env&iacute;o de datos al servidor</span>');      
        }
    }); 
    }else{
           toastr.info('Estado de prospecto sin cambios'); 
}   
});
}
</script>                            