                <div class="row">
					<div class="col-md-12">
						<!-- BEGIN SAMPLE FORM PORTLET-->
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption font-green-haze">
									<i class="icon-user font-green-haze"></i>
									<span class="caption-subject bold uppercase"> Seguimiento de Oportunidad por RUT</span>
								</div>
								<div class="actions">									
									<a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
									</a>
								</div>
							</div>
							<div class="portlet-body form">                            
								<form id="form_seguimiento" method="post" action="<?php echo $this->basePath()?>/operador/oportunidad/rut2" role="form" class="form-horizontal">
									<div class="form-body">
                                                                        
                                    <div id="alertok"></div>
                                    <div id="alertnok"></div>
                                                                        
										<div class="form-group form-md-line-input">
											<div class="row text-center" style="margin-bottom: 10px;">
									  <div class="form-group form-md-line-input">
											<label class="col-md-4 control-label" for="seg_rut">Rut</label>
											<div class="col-md-4">
												<input type="text" class="form-control" id="seg_rut" name="RUT" required>
												<div class="form-control-focus">
												</div>
                                                <span class="help-block">Sin puntos ni DV</span>
											</div>
										</div>
                                        
                                        </div>
                                        <span class="input-group-btn btn-right text-center">
                                            <a id="existe_rut" class="btn green-haze">
                                                    <i class="fa fa-search"></i> &nbsp; Buscar oportunidades creadas
                                            </a>
			                                </span> 
										</div>
                                    </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                   </div>

                                        
<script>
$("#existe_rut").click(function(){
    if($("#seg_rut").val()<1) {
        toastr.warning('Debe ingresar un valor');    
    }else{   
        $.ajax(
            {
            url : '<?php echo $this->basePath()."/operador/oportunidad/existerut"?>',
            type: "POST",
            data : {'RUT' : $("#seg_rut").val()},
            dataType : 'json',
            success : function(response) {                        
              if(response.flag!="true")
                        {
                         toastr.warning(response.descr);  
              }else{
                $("#form_seguimiento").submit(); 
                toastr.success(response.descr); 
              }
            },
            error: function(jqXHR, textStatus, errorThrown) 
            {   
                toastr.error('Error! Favor contactar con administrador del sistema');                            
            }
        }); 
    }  
});

</script>