                <div class="row">
					<div class="col-md-12">
						<!-- BEGIN SAMPLE FORM PORTLET-->
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption font-green-haze">
									<i class="icon-user font-green-haze"></i>
									<span class="caption-subject bold uppercase"> Seguimiento de Oportunidad por RUT</span>
								</div>
								<div class="actions">									
									<a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
									</a>
								</div>
							</div>
							<div class="portlet-body form">                            
								<form id="form_prospecto" action="<?php echo $this->basePath()?>/oportunidad/actualizardatos" role="form" class="form-horizontal">
									<div class="form-body">
                                                                        
                                    <div id="alertok"></div>
                                    <div id="alertnok"></div>
                                                                        
										<div class="form-group form-md-line-input">
											<label class="col-md-4 control-label" for="form_control_1">Rut</label>
											<div class="col-md-4">
												<input type="text" class="form-control" id="form_control_1" name="rut">
												<div class="form-control-focus">
												</div>
                                                <span class="help-block">Sin puntos ni DV</span>
											</div>
                                            <span class="input-group-btn btn-right">
												            <a href="<?php echo $this->basePath()?>/operador/oportunidad/rut2" class="btn green-haze" type="button"><i class="fa fa-search"></i></a>
			                                </span> 
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                   </div>

                                        