                <div class="row">
					<div class="col-md-12">
						<!-- BEGIN SAMPLE FORM PORTLET-->
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption font-green-haze">
									<i class="icon-user font-green-haze"></i>
									<span class="caption-subject bold uppercase"> Seguimiento de Oportunidad por RUT</span>
								</div>
								<div class="actions">									
									<a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
									</a>
								</div>
							</div>
							<div class="portlet-body form">                            								
									<div class="form-body ">
                                                                        
                                    <div id="alertok"></div>
                                    <div id="alertnok"></div>                                                                        																										
															<div class="row static-info">
																<div class="col-md-5 name">
																	 RUT:
																</div>
																<div class="col-md-7 value">
																	 16.532.556-7
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Nombre:
																</div>
																<div class="col-md-7 value">
																	 Tom&aacute;s 
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Apellido Paterno:
																</div>
																<div class="col-md-7 value">
														             Cornejo 
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Apellido Materno:
																</div>
																<div class="col-md-7 value">
																	 Corral 
																</div>
															</div>	
                                                            <br />
                                                            <br />					
               
               <table class="table table-hover">
							<thead>
									<tr>
										<th>
											 Sede
										</th>
										<th>
											 Carrera
										</th>
										<th>
											 Jornada
										</th>
										<th>
											 Estado
										</th>
                                        <th>
					                         &Uacute;ltima Observaci&oacute;n
										</th>
                                        <th>
										     Acci&oacute;n 
										</th>
									</tr>
				            </thead>
							<tbody>
                                <tr>
										<td>
											 Santiago
										</td>
										<td>
											 Admin. Industrial
										</td>
										<td>
											 Diurna
										</td>
										<td>
											 Abierta
										</td>
                                        <td>
					                         Se debe llamar, muy interesado
										</td>
                                        <td>
										    <a onclick="detalle_oportunidad('<?php echo $this->prospecto[0]['RUT'];?>');" data-target="#modal_detalle" data-toggle="modal" class="btn green-haze" ><i class="fa fa-plus"></i></a>
										</td>
									</tr>        <!-- INFO TABLA AQUI !!-->
							</tbody>
				</table>                                                                                                            
                                    </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                
                                </div>
                                
                                

                            </div>
                        </div>
                   </div>
<div id="modal_detalle" class="modal fade" tabindex="-1" role="dialog"  data-keyboard="false">
									<div class="modal-dialog modal-lg">
										<div class="modal-content">
											<div class="modal-header">
												<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
												<h4 class="modal-title"><i class="icon-user"></i> &nbsp;Gesti&oacute;n de feedback de Oportunidad</h4>
											</div>
			<div id="bodymodal_detalle" class="modal-body">
											                 
                                                           
			 </div>
		</div>
    </div>
</div>    
<script>
function detalle_oportunidad(rut){     
postData = {'rut' : rut}      
$.ajax(
    {
        url : '<?php echo $this->basePath()."/operador/oportunidad/rut3"?>',
        type: "POST",
        data : postData,        
		success : function(response) {
		  $('#modal_detalle').modal('show');
		  $("#bodymodal_detalle").html(response);
		},
        error: function(jqXHR, textStatus, errorThrown) 
        {            
            alert("error"); 
        }
    });
}    
</script>                                                                                