                <div class="row">
					<div class="col-md-12">
						<!-- BEGIN SAMPLE FORM PORTLET-->
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption font-green-haze">
									<i class="icon-user font-green-haze"></i>
									<span class="caption-subject bold uppercase"> Seguimiento de Oportunidad por RUT</span>
								</div>
								<div class="actions">									
									<a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
									</a>
								</div>
							</div>
							<div class="portlet-body form">                            								
									<div class="form-body ">                        
                                    <div id="alertok"></div>
                                    <div id="alertnok"></div>                                                                        																										
															<div class="row static-info">
																<div class="col-md-5 name">
																	 RUT:
																</div>
																<div class="col-md-7 value">
															 <?php echo $prospecto[0]['RUT']?>
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Nombre:
																</div>
																<div class="col-md-7 value">
																	 <?php echo $prospecto[0]['NOMBRES']?>
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Apellido Paterno:
																</div>
																<div class="col-md-7 value">
														             <?php echo $prospecto[0]['AP_PATERNO']?>
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Apellido Materno:
																</div>
																<div class="col-md-7 value">
																	  <?php echo $prospecto[0]['AP_MATERNO']?>
																</div>
															</div>	
                                                            <br />
                                                            <br />					
               
               <table class="table table-hover">
							<thead>
									<tr>
										<th>
											 Sede
										</th>
										<th>
											 Carrera
										</th>
										<th>
											 Jornada
										</th>
										<th>
											 Estado
										</th>
                                        <th>
					                         &Uacute;ltima Observaci&oacute;n
										</th>
                                        <th>
										     Acci&oacute;n 
										</th>
									</tr>
				            </thead>
                            <tbody>
                            <?php for ($i=0;$i<count($oportunidad);$i++){ ?>							
                                <tr>
										<td>
											 <?php echo $this->oportunidad[$i]['NOMBRE_SEDE'];?>
										</td>
										<td>
											 <?php echo $this->oportunidad[$i]['NOMBRE_CARRERA'];?>
										</td>
										<td>
											  <?php if($this->oportunidad[$i]['JORNADA']=="V"){echo "Vespertina";}else{echo "Diurna";}?>
										</td>
										<td>
											 <?php echo $this->oportunidad[$i]['ESTADO'];?>
										</td>
                                        <td>
					                         <?php echo $this->oportunidad[$i]['FEEDBACK'];?>
										</td>
                                        <td>
										    <a onclick="detalle_oportunidad('<?php echo $this->prospecto[0]['RUT']."','".$this->oportunidad[$i]['ID_OPORTUNIDAD'];?>');" data-target="#modal_detalle" data-toggle="modal" class="btn green-haze" ><i class="fa fa-plus"></i></a>
										</td>
									</tr> 
                             <?php } ?>                                    
							</tbody>
				</table>                                                                                                            
                                    </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                
                                </div>
                                
                                

                            </div>
                        </div>
                   </div>
<div id="modal_detalle" class="modal fade" tabindex="-1" role="dialog"  data-keyboard="false">
									<div class="modal-dialog modal-lg">
										<div class="modal-content">
											<div class="modal-header">
												<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
												<h4 class="modal-title"><i class="icon-user"></i> &nbsp;Gesti&oacute;n de feedback de Oportunidad</h4>
											</div>
			<div id="bodymodal_detalle" class="modal-body">
											                 
                                                           
			 </div>
		</div>
    </div>
</div>    
<script>
function detalle_oportunidad(rut,id_opor){     
postData = {'rut' : rut,'id_opor' : id_opor}      
$.ajax(
    {
        url : '<?php echo $this->basePath()."/operador/oportunidad/rut3"?>',
        type: "POST",
        data : postData,        
		success : function(response) {
		  $('#modal_detalle').modal('show');

		  $("#bodymodal_detalle").html(response);
;          
		},
        error: function(jqXHR, textStatus, errorThrown) 
        {            
            toastr.error('Error! Favor contactar con administrador del sistema'); 
        }
    });
}    
</script>                                                                                