<div class="row static-info"> 
																<div class="col-md-5 name">
																	 RUT:
																</div>
																<div class="col-md-7 value">
																	 <?php echo $prospecto[0]['RUT']?>
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Nombre:
																</div>
																<div class="col-md-7 value">
																	 <?php echo $prospecto[0]['NOMBRES']?>
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Correo:
																</div>
																<div class="col-md-7 value">
														             <?php echo $prdetalle[0]['CORREO']?>
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Tel&eacute;fono:
																</div>
																<div class="col-md-7 value">
																	 <?php echo $prdetalle[0]['TELEFONO']?> 
																</div>
															</div>
                                                            <div class="row static-info">
																<div class="col-md-5 name">
																	 Celular:
																</div>
																<div class="col-md-7 value">
																	 <?php echo $prdetalle[0]['CELULAR']?> 
																</div>
															</div>
                                                            <div class="row static-info">
																<div class="col-md-5 name">
																	 Emp/Establecimiento:
																</div>
																<div class="col-md-7 value">
																	 <?php echo $prdetalle[0]['EMPRESA_ESTABLEC']?> 
																</div>
															</div>	
                                                            <br />
                                                            <br />
                                                            
                <table class="table table-hover">
				    	<thead>
									<tr>
                                        <th>
											 #
										</th>
										<th>
											 Correo
										</th>
										<th>
											 Tel&eacute;fono
										</th>
										<th>
											 Celular
										</th>
										<th>
											 Empresa/Establec.
										</th>
                                        <th>
										     Direcci&oacute;n 
										</th>
                                        <th>
										      Usuario
										</th>
                                        <th>
										     Fecha 
										</th>
									</tr>
							</thead>
							<tbody>
                                <?php echo $html?>    
					    	</tbody>
				</table>                                
                                                    <div class="row static-info">
                	                                       <div class="col-md-5 name">
																	 Campa&ntilde;a:
																</div>
																<div class="col-md-7 value">
																	 <?php echo $opor_detalle[0]['NOMBRE_CAMPANA'];?> 
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Sede:
																</div>
																<div class="col-md-7 value">
																	 <?php echo $opor_detalle[0]['NOMBRE_SEDE']?>
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Carrera:
																</div>
																<div class="col-md-7 value">
														             <?php echo $opor_detalle[0]['NOMBRE_CARRERA']?>
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Jornada:
																</div>
																<div class="col-md-7 value">
																	 <?php if($this->$opor_detalle[0]['JORNADA']=="V"){echo "Vespertina";}else{echo "Diurna";}?> 
																</div>
															</div>
                                                            <div class="row static-info">
																<div class="col-md-5 name">
																	 &Uacute;ltimo Estado:
																</div>
																<div class="col-md-7 value">
																	  <?php echo $opor_detalle[0]['ESTADO']?>
																</div>
															</div>
                                                            <div class="row static-info">
																<div class="col-md-5 name">
																	 &Uacute;ltima Observaci&oacute;n:
																</div>
																<div class="col-md-7 value">
																	 <?php echo $opor_detalle[0]['FEEDBACK']?> 
																</div>
															</div>
                
                                             <br />
                <form id="form_feedback" role="form">          
                                        <div class="form-group form-md-line-input form-md-floating-label">
											<input type="hidden" name="ID_OPORTUNIDAD" value="<?php echo $opor_detalle[0]['ID_OPORTUNIDAD']?>"/>
                                            <textarea name="OBSERVACION" class="form-control" rows="3" autofocus></textarea>
											<label for="form_control_1">Nueva Observaci&oacute;n</label>
										</div>
                                        
          <div class="portlet-body form">								
									<div class="form-body">
                                    <div class="row text-center">
										<div class="col-md-4 col-md-push-4 form-group form-md-line-input has-info ">
											<select class="form-control" id="combo_estado" name="ESTADO_GRABADO">
												<option value="0">Seleecione un estado</option>
												<option value="Nueva">Nueva</option>
												<option value="Gestionar">Gestionar</option>
												<option value="Gestionada">Gestionada</option>
												<option value="Cerrada">Cerrada</option>
											</select>
											<label for="combo_estado"><strong>Cambiar estado a:</strong></label>
										</div>
						             </div>                                    
                                    <div class="row text-center">
										<div class="col-md-4 col-md-push-4 form-group form-md-line-input has-info ">
											<select class="form-control" onchange="fechaFeedback()" id="combo_feedback" name="ID_TIPO">
                                            <option value="0">Seleccione un tipo de feedback</option>
                                            <?php for ($i=0;$i<count($combofeedback);$i++){                                                      
                                                      echo "<option value=".$combofeedback[$i]['ID_TIPO'].">".$combofeedback[$i]['DESC_TIPO']."</option>\n";
                                               }        
                                                ?>
	
 
											</select>
											<label for="combo_feedback"><strong>Feedback</strong></label>                                            
                                            <input id="fecha_agendamiento" type="datetime" name="FECHA_AGENDAMIENTO" hidden disabled/>
                                            <span id="span_fecha_agendamiento" class="btn green-haze hidden">
                                            Fecha Agendamiento: <span id="span_date"></span>
                                            </span>
										</div>
                                        
						             </div>                                                                                                                                                   
								</form>
							</div>
                </div>
                <div class="portlet-body form text-right">
                  <button type="button" data-dismiss="modal" class="btn">Close</button>
               <a onclick="guardafeedback()"  class="btn blue">Guardar Feedback</a>        
               </div>   

<script>
toastr.options = {
  "positionClass": "toast-top-center",
}
function guardafeedback(){
    var combo1 = $("#combo_estado").val();
    var combo2 = $("#combo_feedback").val();
if(combo1<1 || combo2<1){
    toastr.warning("Debe seleccionar un estado y tipo de feedback"); 
}else{ 
    var postData = $("#form_feedback").serializeArray();
    $.ajax(
        {
            url : '<?php echo $this->basePath()."/operador/oportunidad/nuevofeedback"?>',
            type: "POST",
            data : postData,        
		  success : function(response) {
		      if(response.status =="ok"){
                $('#modal_detalle').modal('hide');   
                toastr.success('Feedback guardado exitosamente');
                window.setTimeout(function() {
                window.location.reload(true);
                }, 1000)
                                
                }     
	   	},
         error: function(jqXHR, textStatus, errorThrown) 
            {            
                toastr.error('Error! Favor contactar con administrador del sistema'); 
            }
        });
}    
}
function Today(){
    var now = new Date();

var day = ("0" + now.getDate()).slice(-2);
var month = ("0" + (now.getMonth() + 1)).slice(-2);

var today = now.getFullYear()+"-"+(month)+"-"+(day)+" "+now.getHours()+":"+now.getMinutes()+":"+now.getSeconds();
return today;

}
function TodayChile(){
    var now = new Date();

var day = ("0" + now.getDate()).slice(-2);
var month = ("0" + (now.getMonth() + 1)).slice(-2);

var today = (day)+"-"+(month)+"-"+now.getFullYear();
return today;

}
function fechaFeedback(){
    var value = $("#combo_feedback").val();
    var texto = $("#combo_feedback").text();
    if (value==3||texto=="Agendamiento"){
        
        $("#span_fecha_agendamiento").removeClass("hidden");
        $("#fecha_agendamiento").removeAttr("disabled");
        var today = Today();
        $('#fecha_agendamiento').val(today); 
        $('#span_date').text(TodayChile());
               
}else{
     $("#span_fecha_agendamiento").addClass("hidden");    
     $("#fecha_agendamiento").attr("disabled","true");     
    
}
    
}
</script>            