<div class="row static-info">
																<div class="col-md-5 name">
																	 RUT:
																</div>
																<div class="col-md-7 value">
																	 16.532.556-7
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Nombre:
																</div>
																<div class="col-md-7 value">
																	 Tom&aacute;s Cornejo C.
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Correo:
																</div>
																<div class="col-md-7 value">
														             tcornejo01@gmail.com 
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Tel&eacute;fono:
																</div>
																<div class="col-md-7 value">
																	 26889544 
																</div>
															</div>
                                                            <div class="row static-info">
																<div class="col-md-5 name">
																	 Celular:
																</div>
																<div class="col-md-7 value">
																	 54103054 
																</div>
															</div>
                                                            <div class="row static-info">
																<div class="col-md-5 name">
																	 Emp/Establecimiento:
																</div>
																<div class="col-md-7 value">
																	 Particular 
																</div>
															</div>	
                                                            <br />
                                                            <br />
                                                            
                <table class="table table-hover">
				    	<thead>
									<tr>
										<th>
											 Correo
										</th>
										<th>
											 Tel&eacute;fono
										</th>
										<th>
											 Celular
										</th>
										<th>
											 Empresa/Establec.
										</th>
                                        <th>
										     Direcci&oacute;n 
										</th>
                                        <th>
										     Fecha 
										</th>
                                        <th>
										     Usuario 
										</th>
									</tr>
							</thead>
							<tbody>
                                       <tr>
										<td>
											 tcornejo01@gmail.com
										</td>
										<td>
											54111322
										</td>
										<td>
											 99332112
										</td>
                                        <td>
											 Tarapaca 876
										</td>
										<td>
											 Particular
										</td>
                                        <td>
					                        27-09-2015
										</td>
                                        <td>
										    operadorA
										</td>
									</tr>        <!-- INFO TABLA AQUI !!-->
					    	</tbody>
				</table>                                
                                                    <div class="row static-info">
                	                                       <div class="col-md-5 name">
																	 Campa&ntilde;a:
																</div>
																<div class="col-md-7 value">
																	 Campa&ntilde;a Liceo XY
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Sede:
																</div>
																<div class="col-md-7 value">
																	 Santiago
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Carrera:
																</div>
																<div class="col-md-7 value">
														             Administraci&oacute;n Industrial 
																</div>
															</div>
															<div class="row static-info">
																<div class="col-md-5 name">
																	 Jornada:
																</div>
																<div class="col-md-7 value">
																	 Diurna 
																</div>
															</div>
                                                            <div class="row static-info">
																<div class="col-md-5 name">
																	 &uacute;ltimo Estado:
																</div>
																<div class="col-md-7 value">
																	 Abierta 
																</div>
															</div>
                                                            <div class="row static-info">
																<div class="col-md-5 name">
																	 &uacute;ltima Observaci&oacute;n:
																</div>
																<div class="col-md-7 value">
																	 Particular 
																</div>
															</div>
                
                                             <br />
                                                  
                                        <div class="form-group form-md-line-input form-md-floating-label">
											<textarea  class="form-control" rows="3" autofocus></textarea>
											<label for="form_control_1">Nueva Observaci&oacute;n</label>
										</div>
                                        
          <div class="portlet-body form">
								<form role="form">
									<div class="form-body">
                                    <div class="row text-center">
										<div class="col-md-4 col-md-push-4 form-group form-md-line-input has-info ">
											<select class="form-control" id="form_control_1">
												<option value=""></option>
												<option value="">Option 1</option>
												<option value="">Option 2</option>
												<option value="">Option 3</option>
												<option value="">Option 4</option>
											</select>
											<label for="form_control_1"><strong>Cambiar estado a:</strong></label>
										</div>
						             </div>
                                     <div class="row text-center">
										<div class="col-md-4 col-md-push-4 form-group form-md-line-input has-info ">
											<select class="form-control" id="form_control_1">
												<option value=""></option>
												<option value="">Option 1</option>
												<option value="">Option 2</option>
												<option value="">Option 3</option>
												<option value="">Option 4</option>
											</select>
											<label for="form_control_1"><strong>Feedback</strong></label>
										</div>
						             </div>                                                                                                              
								</form>
							</div>
                </div>
                <div class="portlet-body form text-right">
                  <button type="button" data-dismiss="modal" class="btn">Close</button>
               <button type="button" class="btn blue">Guardar Feedback</button>        
               </div>        