<div class="portlet-body form">
								<!-- BEGIN FORM-->
								<form action="#" class="form-horizontal form-bordered">
									<div class="form-body">
										<div class="form-group">
											<label class="control-label col-md-3">Carga maestra de oportunidades</label>
											<div class="col-md-9">
												<div class="fileinput fileinput-new" data-provides="fileinput">
													<div class="input-group input-large">
														<div class="form-control uneditable-input input-fixed input-medium" data-trigger="fileinput">
															<i class="fa fa-file fileinput-exists"></i>&nbsp; <span class="fileinput-filename">
															</span>
														</div>
														<span class="input-group-addon btn default btn-file">
														<span class="fileinput-new">
														Seleccionar archivo </span>
														<span class="fileinput-exists">
														Cambiar </span>
														<input type="file" name="...">
														</span>
														<a href="javascript:;" class="input-group-addon btn red fileinput-exists" data-dismiss="fileinput">
														Quitar </a>
													</div>
												</div>
											</div>
										</div>
                                        <br />
							<div class="portlet-body">
								<div class="table-responsive">
									<table class="table">
									<thead>
									<tr>
										<th>
											 Nombre
										</th>
										<th>
											 Apellido 
										</th>
                                        <th>
											 Correo 
										</th>
										<th>
											 Telefono
										</th>
										<th>
											 Empresa/Establec.
										</th>
                                        <th>
											 Estado
										</th>
									</tr>
									</thead>
									<tbody>
									<?php //echo $html?>								
									</tbody>
									</table>
								</div>
							</div>
						