
<div class="portlet-body form">
								<!-- BEGIN FORM-->
								<form action="#" class="form-horizontal form-bordered">
									<div class="form-body">
										<div class="form-group">
											<label class="control-label col-md-4"><strong>Carga maestra de prospectos</strong></label>
											<div class="col-md-8">
												<div class="fileinput fileinput-new" data-provides="fileinput">
													<div class="input-group input-large">
														<div class="form-control uneditable-input input-fixed input-medium" data-trigger="fileinput">
															<i class="fa fa-file fileinput-exists"></i>&nbsp; <span class="fileinput-filename">
															</span>
														</div>
														<span class="input-group-addon btn default btn-file">
														<span class="fileinput-new">
														Seleccionar archivo </span>
														<span class="fileinput-exists">
														Cambiar </span>
														<input type="file" id="fileprospectos" name="..." onchange="ValidaRUT()">
														</span>
														<a href="javascript:;" class="input-group-addon btn red fileinput-exists" data-dismiss="fileinput">
														Quitar </a>                                                        
													</div>
												</div>
											</div>
										</div>          
                                        <div class="form-group form-md-line-input">										
											<div class="col-md-offset-4">																								
                                                <a id="btn_carga" onclick="cargaProspectos()" class="btn green hide"><i class="fa fa-spinner"></i> &nbsp;Cargar Prospectos</a>                                                											
										   </div>
                                        </div>                              										          
                                        <br />
							<div id="tabla_carga" class="portlet-body hide">
								<div class="table-responsive">
									<table class="table">
									<thead>
									<tr>
                                        <th>
											 Rut
										</th>
										<th>
											 Nombres
										</th>
										<th>
											 Apellidos
										</th>
                                        <th>
											 Correo 
										</th>
										<th>
											 Telefono
										</th>
										<th>
											 Empresa/Establec.
										</th>
                                        <th>
											 Estado
										</th>
									</tr>
									</thead>
									<tbody id="body_tabla_carga">							
									</tbody>
									</table>
								</div>
							</div>
                            </div>
                            </form>
                            </div>
<script>
toastr.options = {
  "positionClass": "toast-top-center",
}
function ValidaRUT(){
if($('#fileprospectos').val()!=""){
var data = new FormData();
    jQuery.each(jQuery('#fileprospectos')[0].files, function(i, file) {
    data.append('file-'+i, file);
    });    
       
$.ajax( {
	    url : '<?php echo $this->basePath()."/admincentral/cargas/checkprospectos"?>',
		data : data,
        cache: false,
        contentType: false,
        processData: false,
        type: 'POST',   
		success : function(response) {		  
          if(response.status == 'ok'){
            $("#btn_carga").removeClass("hide");              
            toastr.success("Todos los rut pueden ser cargados");                                     
          }else
          {
            toastr.warning(response.descr);
          }
		},
        error: function(jqXHR, textStatus, errorThrown) 
        {
            toastr.error('Error ! Favor contactar con administrador del sistema');            
           // $("#alertnok").html('<span class="alert alert-success">Error en el env&iacute;o de datos al servidor</span>');      
        }
	}); 
}       
}
function cargaProspectos(){    
var data = new FormData();
    jQuery.each(jQuery('#fileprospectos')[0].files, function(i, file) {
    data.append('file-'+i, file);
    });        
	$.ajax( {
	    url : '<?php echo $this->basePath()."/admincentral/cargas/cargaprospectos"?>',
		data : data,
        cache: false,
        contentType: false,
        processData: false,
        type: 'POST',   
		success : function(response) {		  
          if(response.status == 'ok'){
            $("#tabla_carga").removeClass("hide"); 
            $("#body_tabla_carga").append(response.html); 
            toastr.success(response.descr)                                     
          }else
          {
            toastr.warning(response.descr);
          }
		}
	}); 
}
</script>						
