
<!-- BEGIN BODY -->
<body class="login">
<!-- BEGIN LOGO -->
<div class="logo">
	Instituto Profesional La Araucana
</div>
<!-- END LOGO -->
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGIN -->
<div class="content">
	<!-- BEGIN LOGIN FORM -->
	<form id="logueo" class="login-form" action="<?php echo $this->basePath()?>/application/login/send" method="post">
		<h3 class="form-title">Ingresar al sistema</h3>
		<div class="alert alert-danger display-hide">
			<button class="close" data-close="alert"></button>
			<span>
			Ingrese usuario y contrase&ntilde;a. </span>
		</div>
        <?php if(isset($mensaje)){?>
        <div id="alerta" class="alert alert-danger">
			<button class="close" data-close="alert"></button>
			<span><?php echo $mensaje ?></span>
		</div>
        <?php }?>
		<div class="form-group">
			<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
			<label class="control-label visible-ie8 visible-ie9">Usuario</label>
			<div class="input-icon">
				<i class="fa fa-user"></i>
				<input id="uuario" class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Usuario" name="usuario"/>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label visible-ie8 visible-ie9">Password</label>
			<div class="input-icon">
				<i class="fa fa-lock"></i>
				<input id="password" class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Contrase&ntilde;a" name="password"/>
                <input class="form-control" name="password2" id="password2" type="hidden" />
			</div>
		</div>
		<div class="form-actions">
			<label class="checkbox">
			<input type="checkbox" name="remember" value="1"/> Recordar </label>
			<button id="iniciar" type="submit" class="btn blue pull-right">
			Ingresar <i class="m-icon-swapright m-icon-white"></i>
			</button>
		</div>
		<!--div class="login-options">
			<h4>Or login with</h4>
			<ul class="social-icons">
				<li>
					<a class="facebook" data-original-title="facebook" href="javascript:;">
					</a>
				</li>
				<li>
					<a class="twitter" data-original-title="Twitter" href="javascript:;">
					</a>
				</li>
				<li>
					<a class="googleplus" data-original-title="Goole Plus" href="javascript:;">
					</a>
				</li>
				<li>
					<a class="linkedin" data-original-title="Linkedin" href="javascript:;">
					</a>
				</li>
			</ul>
		</div-->
		<!--div class="forget-password">
			<h4>Olvidaste tu contrase&ntilde;a ?</h4>
			<p>
				 No te preocupes, haz click <a href="javascript:;" id="forget-password">
				aqu&iacute; </a>
				para reestablecer tu contrase&ntilde;a.
			</p>
		</div-->
		<!--div class="create-account">
			<p>
				 Don't have an account yet ?&nbsp; <a href="javascript:;" id="register-btn">
				Create an account </a>
			</p>
		</div-->
	</form>
	<!-- END LOGIN FORM -->
	<!-- BEGIN FORGOT PASSWORD FORM -->
	<form class="forget-form" action="index.html" method="post">
		<h3>Contrase&ntilde;a olvidada ?</h3>
		<p>
			 Ingresa tu correo electr&oacute;nico para reestablecer tu contrase&ntilde;a.
		</p>
		<div class="form-group">
			<div class="input-icon">
				<i class="fa fa-envelope"></i>
				<input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email"/>
			</div>
		</div>
		<div class="form-actions">
			<button type="button" id="back-btn" class="btn">
			<i class="m-icon-swapleft"></i> Atr&aacute;s </button>
			<button type="submit" class="btn blue pull-right">
			Enviar <i class="m-icon-swapright m-icon-white"></i>
			</button>
		</div>
	</form>
	<!-- END FORGOT PASSWORD FORM -->
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
	 CRM Admisi&oacute;n
</div>
</body>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script>
    $(document).ready(function(e){
        $('#usuario').focus();
        $('#iniciar').click(function(e){
            var pass = hex_md5($("#password").val());
            var pass = binHash(pass);
            $("#password2").val(pass);
            $("#password").attr("disabled", "disabled");
            $('form#logueo').submit();
            
        });
        $('#password').keypress(function (e) {
            if (e.which == 13) {
            var pass = hex_md5($("#password").val());
            var pass = binHash(pass);
            $("#password2").val(pass);
            $("#password").attr("disabled", "disabled");
            $('form#logueo').submit();
                }
            });
        
    });
$("#formemail").submit(function(e)
{
    var postData = $(this).serializeArray();
    var formURL = $(this).attr("action");
    $.ajax(
    {
        url : formURL,
        type: "POST",
        data : postData,
        dataType : 'json',
        success : function(response) {
                    
          $("#mostrarEmail").html('<div id="respuesta" class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'+response.descripcion+'</div>');                                
          $("#mostrarEmail").fadeOut(5000);
          if (response.status == "ok"){
          $("#enviarformemail").attr('disabled', 'disabled');
          }
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {
            $("#mostrarEmail").html('<div id="respuesta" class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>Error en el env&iacute;o de datos al servidor</div>')      
        }
    });
    e.preventDefault(); //STOP default action    
});       
    </script>