<?php
//LLamaremos a la session
use Zend\Session\Container;
$sid = new Container('base');
$url = $this->basePath();
if ($sid->offsetGet('logueado')!="si"){     
     header ("Location: $url/application/login");
    exit;
};
$modulo = $sid->offsetGet('urlHome');
if ($modulo!="adminsede"){
    header ("Location: $url/$modulo");
    exit;
 }
?>
<?php echo $this->doctype(); ?>
<html lang="es">
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div> 
    </body>
</html>
