<form action="" method="post" id="form_campana">
<div class="row">
										<div class="col-md-8 col-md-push-2 form-group form-md-line-input has-info ">
											<select class="form-control" id="combo_tipocam" name="ID_TIPO">
                                            <option value="0">Seleccione un tipo de campa&ntilde;a</option>
                                            <?php for ($i=0;$i<count($combocampana);$i++){
                                                    $selected="";
                                                    if($combocampana[$i]['ID_TIPO']==$campana[0]['ID_TIPO']){$selected="selected";}
                                                      echo "<option ".$selected." value=".$combocampana[$i]['ID_TIPO'].">".$combocampana  [$i]['DESC_TIPO']."</option>\n";
                                               }        
                                                ?>	 
											</select>											
										</div>
 </div> 
<div class="form-group form-md-line-input">
											<label class="col-md-4 control-label" for="camp_nombre"><strong>Nombre Campa&ntilde;a</strong></label>
											<div class="col-md-6">
												<input value="<?php echo $campana[0]['NOMBRE_CAMPANA'];?>" type="text" class="form-control" id="camp_nombre" name="NOMBRE_CAMPANA" required>
                                                <input name="ID_CAMPANA" type="hidden" value="<?php echo $campana[0]['ID_CAMPANA'];?>" />
												<div class="form-control-focus">
												</div>
                                                <!--span class="help-block">Sin puntos ni DV</span-->
											</div>
</div>
<div class="form-group form-md-line-input ">
<label class="col-md-4 control-label" ><strong>Estado</strong></label>

										<div class="md-radio-inline">
											<div class="md-radio">
												<input type="radio" id="radio6" value="s" name="ACTIVO" class="md-radiobtn" <?php if($campana[0]['ACTIVO']=="s"){ echo "checked";}?> >
												<label for="radio6">
												<span></span>
												<span class="check"></span>
												<span class="box"></span>
												Activa </label>
											</div>
											<div class="md-radio">
												<input type="radio" id="radio7" value="n" name="ACTIVO" class="md-radiobtn" <?php if($campana[0]['ACTIVO']=="n"){ echo "checked";}?> >
												<label for="radio7">
												<span></span>
												<span class="check"></span>
												<span class="box"></span>
												No activa </label>
											</div>
									</div>
</div>                                    
<div class="form-group form-md-checkboxes">
										<label>Seleccione NUEVAS sedes que desea asociar</label>
										<div class="md-checkbox-inline">
                                        <?php 
                                                for($i=0;$i<count($sedes);$i++){
                                                    $check="";
                                                    $disabled="";
                                                    for($j=0;$j<count($sedecampanas);$j++){ 
                                                        if(in_array($sedes[$i]['COD_SEDE'],$sedecampanas[$j])){                                                           
                                                            $check="checked";
                                                            $disabled="disabled";
                                                        }
                                                    }             
                                                echo '
											<div class="md-checkbox has-success">
												<input name="COD_SEDE[]" type="checkbox" value="'.$sedes[$i]['COD_SEDE'].'" id="checkbox'.$i.'" class="md-check" '.$check.' '.$disabled.'>
												<label for="checkbox'.$i.'">
												<span></span>
												<span class="check"></span>
												<span class="box"></span>
												 '.$sedes[$i]['NOMBRE_SEDE'].'</label>
											</div>';} ?> 											
										</div>
</div>
<br />
<div class="form-group form-md-line-input">										
											<div class="col-md-offset-4">												
												<a class="btn red" data-dismiss="modal" aria-hidden="true"><i class="fa fa-close"></i> &nbsp; Cancelar</a>
                                                <a onclick="validaInput()" class="btn green"><i class="fa fa-edit"></i> &nbsp;Editar campa&ntilde;a</a>                                                											
										   </div>
</div>
</form>
<script>
function validaInput(){
  if($("#combo_tipocam").val()<1 || $("#camp_nombre").val()<1){
        toastr.warning('Debes seleccionar un tipo y dar un nombre a la campaña');
  }else{
    editarCampana()
  }
}
function editarCampana(){
bootbox.confirm("<strong>Se editar&aacute; la campa&ntilde;a, esta seguro ?", function(result) {
    if (result){      
      var postData = $("#form_campana").serializeArray();
      $.ajax(
        {
          url : '<?php echo $this->basePath()."/admincentral/administrar/editarcampana"?>',
            type: "POST",
            data : postData,
            dataType : 'json',
            success : function(response) {
                $('#modal_nueva').modal('hide');
                                  window.setTimeout(function() {
                window.location.reload(true);
                }, 800)
                toastr.success(response.descr);
        },
        error: function(jqXHR, textStatus, errorThrown) 
        {
            toastr.error('Error ! Favor contactar con administrador del sistema');            
           // $("#alertnok").html('<span class="alert alert-success">Error en el env&iacute;o de datos al servidor</span>');      
        }
    });                  
    }else{
    toastr.info('Sin cambios'); 
} 
    
});
}
</script>   